language: node_js
node_js:
  - "4"

# required for reasons: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install

script: gulp build

deploy:
  provider: azure_web_apps
  local_dir: dist
