branches:
  only:
    - master
version: '{build}'
clone_depth: 1
install:
- npm -g install npm@2
- npm install gulp
- npm install bower
- npm install
- node_modules\.bin\bower install
build_script:
- node_modules\.bin\gulp build
cache:
- node_modules -> package.json
artifacts:
- path: dist
deploy:
- provider: WebDeploy
  server: https://zoltu-bags-admin-client.scm.azurewebsites.net:443/msdeploy.axd?site=zoltu-bags-admin-client
  website: zoltu-bags-admin-client
  username: $zoltu-bags-admin-client
  password:
    secure: G1JjP0DdHLGBO3KZTiI+hFtHWZDAo077L2GeW2AxWiUPeYzYI1bfc4Tx21jKnADkck24jWSDEno6BH3D4g0ZJg==
  artifact: dist.zip
